version: "3.7"
services:
  common: &common
    build: .
    image: hay
    stdin_open: false
    working_dir: /root
    volumes:
      - ../app:/root
  make: &make
    <<: *common
    command: bash -c 'make'
  makeAndSend: &makeAndSend
    <<: *common
    command: bash -c 'make && nxlink -a $SWITCH_IP ./FreshHay.nro'
